version: "3.7"

volumes:
  db_volume:

services:
  weather_mke:
    build: weather
    image: weather_mke:0.0.1
    container_name: weather_app
    restart: always
    # TODO: Change to 'false' before deployment
    privileged: true
    network_mode: host
    environment:
      CITY: milwaukee
      DB_IP_ADDRESS: 0.0.0.0
      DB_API_PORT: 8086
      TESTING_DB_NAME: example
      TESTING_DB_USER: default
      PROD_DB_NAME: weather
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    depends_on:
      - db

  db:
    build: influxdb
    image: influxdb:main
    container_name: influxdb
    restart: always
    # TODO: Change to false before deployment
    privileged: true
    network_mode: host
#    ports:
#    - "8086:8086"
    volumes:
    - db_volume:/var/lib/influxdb25

