version: "2"

volumes:
  db_persist:

services:
  weather_app:
    build: ./src/weather
    restart: always
    # TODO: Change to false before deployment
    privileged: true
    network_mode: host
    environment:
      DB_IP_ADDRESS: 0.0.0.0
      DB_API_PORT: 8086
      TESTING_DB_NAME: example
      TESTING_DB_USER: default
    ports:
    - 8086:8086

    depends_on:
      - db

  db:
    build: ./src/influxdb
    restart: always
    # TODO: Change to false before deployment
    privileged: true
    network_mode: host
    ports:
    - 8086:8086
    volumes:
    - db_persist:/var/lib/influxdb

